name: deploy-ecs

on:
  push:
    tags:
      - deploy**

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Render task definition
        id: render-ecs-service
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: td-ecs-service.json
          container-name: demo
          image: ${{ steps.login-ecr.outputs.registry }}/<repo-name>:latest

      - name: Deploy ECS service
        timeout-minutes: 10
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-ecs-service.outputs.task-definition }}
          service: ecs-demo-service
          cluster: ecs-demo
          wait-for-service-stability: true

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
